name = "ccr"
main = "worker.js"
compatibility_date = "2024-09-07"
compatibility_flags = ["nodejs_compat"]

[vars]
# These are default values that can be overridden during deployment
# ANTHROPIC_PROXY_BASE_URL = "https://openrouter.ai/api"
# REASONING_MODEL = "x-ai/grok-4-fast:free"
# COMPLETION_MODEL = "x-ai/grok-4-fast:free"
# REASONING_MODEL = "qwen/qwen3-coder:free"
# COMPLETION_MODEL = "qwen/qwen3-coder:free"
REASONING_MODEL =  "z-ai/glm-4.5-air:free"
COMPLETION_MODEL = "z-ai/glm-4.5-air:free"
# DEBUG = "0"
# DEBUG = "0"

# Add secrets in the dashboard or using:
# wrangler secret put OPENROUTER_API_KEY

[build]
command = ""

[env.production]
name = "anthropic-proxy"
